import { Geist } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";


import {
  ClerkProvider
} from '@clerk/nextjs'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Get me a chain - Fund your project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable}`}>
          <Navbar />
          <div className="min-h-[88vh] bg-neutral-900">
            <div className="absolute inset-0 bg-amber-800 bg-[size:20px_20px] opacity-20 blur-[100px] pointer-events-none"></div>
            {children}
          </div>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
} 